/**
 * TestSprite Generated Jest Configuration
 * Optimized for HeartVoice Monitor API Testing
 * Generated by: TestSprite MCP v1.0.0
 */

// Simplified Jest configuration without Next.js dependency
const customJestConfig = {
  // Test environment
  testEnvironment: 'node',
  
  // Setup files
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  
  // Test patterns
  testMatch: [
    '<rootDir>/tests/**/*.test.ts',
    '<rootDir>/tests/**/*.test.js'
  ],
  
  // Coverage configuration
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html', 'json'],
  collectCoverageFrom: [
    'heartvoice-monitor/src/app/api/**/*.ts',
    'heartvoice-monitor/src/services/**/*.ts',
    '!heartvoice-monitor/src/**/*.d.ts',
    '!heartvoice-monitor/src/**/*.config.ts'
  ],
  
  // Coverage thresholds for clinical quality
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80
    },
    // Critical APIs require higher coverage
    'heartvoice-monitor/src/app/api/voice-analysis/': {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90
    },
    'heartvoice-monitor/src/app/api/voice-calls/': {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90
    },
    'heartvoice-monitor/src/app/api/patients/': {
      branches: 85,
      functions: 85,
      lines: 85,
      statements: 85
    }
  },
  
  // Module name mapping
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/heartvoice-monitor/src/$1',
    '^@/components/(.*)$': '<rootDir>/heartvoice-monitor/src/components/$1',
    '^@/services/(.*)$': '<rootDir>/heartvoice-monitor/src/services/$1',
    '^@/types/(.*)$': '<rootDir>/heartvoice-monitor/src/types/$1'
  },
  
  // Transform configuration
  transform: {
    '^.+\\.(ts|tsx)$': ['ts-jest', {
      tsconfig: 'heartvoice-monitor/tsconfig.json'
    }]
  },
  
  // Test timeout for clinical environments
  testTimeout: 30000, // 30 seconds for integration tests
  
  // Verbose output for debugging
  verbose: true,
  
  // Globals for test environment
  globals: {
    'ts-jest': {
      tsconfig: 'heartvoice-monitor/tsconfig.json'
    }
  },
  
  // Mock configuration
  clearMocks: true,
  restoreMocks: true,
  
  // Test results processor
  reporters: ['default'],
  
  // Environment variables for testing
  setupFiles: ['<rootDir>/tests/env.setup.js']
};

// Export the Jest configuration directly
module.exports = customJestConfig;
